spring:
    main: 
        allow-circular-references: true
    application:
        name: vehicle-rental-2306203236-be

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    
    profiles:
        active: 'dev'

    jpa:
        hibernate:
            ddl-auto: create-drop

vehicle-rental-2306203236-be:
    app: 
        jwtSecret: "${JWT_SECRET_KEY}"
        jwtExpirationMs: 86400000

vehicle:
   api-key: ${API_KEY_APAP}
    # api-key: "${VEHICLE_API_KEY:test-api-key-dev}" #test
