apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclerental-2306203236-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2306203236-vehiclerental-be
  template:
    metadata:
      labels:
        app: 2306203236-vehiclerental-be
    spec:
      containers:
        - name: springboot-container
          image: kadeksavitri/vehiclerental-2306203236-be:REPLACE_ME_TAG
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DATABASE_URL_PROD
              valueFrom:
                configMapKeyRef:
                  name: vehiclerental-2306203236-be-config
                  key: DATABASE_URL_PROD
            - name: PROD_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: vehiclerental-2306203236-be-config
                  key: DATABASE_USERNAME
            - name: PROD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vehiclerental-2306203236-be-secret
                  key: DATABASE_PASSWORD
            # - name: DATABASE_USERNAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: vehiclerental-2306203236-be-config
            #       key: DATABASE_USERNAME
            # - name: DATABASE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: vehiclerental-2306203236-be-secret
            #       key: DATABASE_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: vehiclerental-2306203236-be-secret
                  key: JWT_SECRET_KEY
            - name : CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: vehiclerental-2306203236-be-secret
                  key: CORS_ALLOWED_ORIGINS
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: vehiclerental-2306203236-be-secret
                  key: API_KEY
            - name: PROFILE_SERVICE_BASE_URL
              value: "https://2306219575-be.hafizmuh.site"