apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2306203236-vehiclerental-be-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: 2306203236-be.hafizmuh.site 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vehiclerental-2306203236-be-service
                port:
                  number: 80